name: Run the tests

on: [pull_request]

env:
  PREFIX_LINUX: /usr/share/miniconda3/envs/gait_analyzer

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]  # windows-latest, macos-latest
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/biobuddy
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code with submodule
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest

      - name: Install dependencies
        run: | 
          pip install . && pip uninstall -y gait_analyzer
          pip install scipy numpy lxml ezc3d matplotlib plotly
          conda install biorbd graphviz biobuddy -cconda-forge

      - name: Install extra dependencies
        run: | 
          conda install pytest-cov black pytest packaging -cconda-forge
          sudo apt install -y librhash-dev

      - name: List conda packages
        run: conda list

      - name: Run tests with code coverage
        run: pytest -v --color=yes --cov-report=xml --cov=gait_analyzer tests

      - name: Send Codecov report
        id: archive
        uses: codecov/codecov-action@v5
        with:
          path: .coverage
          if-no-files-found: error
          fail_ci_if_error: true
          verbose: true
        if: matrix.os == 'ubuntu-latest'

      - name: Generate XML report
        run: |
          coverage xml
          coverage report -m

      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true

      - name: Test installed version of gait_analyzer
        run: |
          python setup.py install
          cd
          python -c "import gait_analyzer"
        if: matrix.shard == 1
